-- The taking half of the assessment domain: a student's session and the answers in it (#58, #59).
-- Auto-generated by drizzle-kit; the freeze trigger that guards `assessment_responses` is a
-- separate hand-written migration (0007), following the split 0000/0001 and 0003/0004 already use.
--
-- ROLLBACK — READ BEFORE RUNNING. This is the one migration on this branch with a point of no
-- return, and the two halves are not equally safe:
--
--   * Rolling back 0007 (the trigger) is ALWAYS lossless. It removes a guarantee, never a row.
--   * Rolling back THIS migration is lossless ONLY while both tables are still empty.
--
--     DROP TABLE assessment_responses;
--     DROP TABLE assessment_sessions;
--
--     Once a student has started or submitted, these tables hold the only copy of their answers.
--     Dropping them destroys real responses and breaks the "Tidak ada loss of submitted
--     responses" SLO in docs/engineering/observability.md outright. There is no forward fix after
--     the fact: the response set is what NFR-11 makes a score traceable to, so losing it makes
--     every score derived from it irreproducible. Restore from backup instead of rolling forward.
--
-- Note for any future migration that REBUILDS either table (SQLite has no ALTER TABLE … ADD
-- CONSTRAINT, so widening a CHECK means exactly that): 0007's triggers are dropped along with the
-- table they guard and MUST be recreated in the same migration, or the freeze silently disappears
-- and nothing detects it. `server/tests/integration/taking-freeze.test.ts` asserts the triggers
-- exist after ALL migrations have run, not merely after 0007.

CREATE TABLE `assessment_responses` (
	`session_id` text NOT NULL,
	`version_item_id` text NOT NULL,
	`answer_value` real NOT NULL,
	PRIMARY KEY(`session_id`, `version_item_id`),
	FOREIGN KEY (`session_id`) REFERENCES `assessment_sessions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`version_item_id`) REFERENCES `assessment_version_items`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `assessment_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`version_id` text NOT NULL,
	`status` text DEFAULT 'in_progress' NOT NULL,
	`consent_policy_version` text NOT NULL,
	`started_at` integer NOT NULL,
	`submitted_at` integer,
	FOREIGN KEY (`version_id`) REFERENCES `assessment_versions`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "assessment_sessions_status_check" CHECK("assessment_sessions"."status" IN ('in_progress', 'submitted', 'scored')),
	CONSTRAINT "assessment_sessions_submitted_at_check" CHECK("assessment_sessions"."status" = 'in_progress' OR "assessment_sessions"."submitted_at" IS NOT NULL)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `assessment_sessions_user_id_version_id_key` ON `assessment_sessions` (`user_id`,`version_id`);